name: container-ci

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  find-jobs:
    name: Find Containers to Build
    runs-on: ubuntu-latest
    env:
      containers_path: ./containers
    outputs:
      folders: ${{ steps.set-folders.outputs.folders }}
    steps:
    - uses: actions/checkout@v4
    - name: List Folders
      id: set-folders
      shell: bash
      run: |
        cd $containers_path
        folders=$(tree -J -d -L 1 | jq -c '.[0].contents | map(.name)')
        echo $folders
        echo "folders=$folders" >> $GITHUB_OUTPUT

  build-push:
    name: Build and Push 
    runs-on: ubuntu-latest
    needs: find-jobs
    strategy:
      matrix:
        folder: ${{ fromJson(needs.find-jobs.outputs.folders) }}
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PUSH_TOKEN }}
    - uses: actions/checkout@v4
    - name: Build and Push Container
      env:
        GHCR_OWNER: ${{ github.actor }}
      run: make container IMAGE=${{ matrix.folder }}

  wsl-export:
    name: Export WSL Archive
    runs-on: ubuntu-latest
    needs: build-push
    steps:
  - uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GHCR_PUSH_TOKEN }}
  - uses: actions/checkout@v4
  - name: Run Container and Export Archive
    env:
      GHCR_OWNER: ${{ github.actor }}
    run: make wsl IMAGE=${{ needs.build-push.matrix.folder }}
  - uses: actions/upload-artifact@v4
    with:
      name: wsl-${{ needs.build-push.matrix.folder }}
      path: wsl-${{ needs.build-push.matrix.folder }}.tar
      overwrite: true


