name: container-ci

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  find-jobs:
    name: Find Containers to Build
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.jobs.outputs.folders }}
    steps:
      - uses: actions/checkout@v1
      - id: jobs
        uses: philips-labs/list-folders-action@v1
        with:
          path: ./containers

  build-push:
    name: Build and Push 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.find-jobs.outputs.folders) }}
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PUSH_TOKEN }}
    - uses: actions/checkout@v4
    - name: Build and Push Container
      env:
        GHCR_OWNER: ${{ github.actor }}
      run: make IMAGE_DIR=${{ matrix.folder }}
