name: container-ci

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
    - name: Build and Push Container
      env:
        GHCR_OWNER: $GHCR_USERNAME
      run: make
