name: container-ci

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:      
  build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v4
    - name: Build and Push Container
      env:
        GHCR_OWNER: ${{ github.actor }}
      run: make
